name: Build MLauncher
on:
  push:
    branches: [ main ]
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: EML-Template-main
      - name: Build Windows
        run: npm run release:win
        working-directory: EML-Template-main
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MLauncher-Setup
          path: |
            EML-Template-main/release/*.exe
            EML-Template-main/release/*.blockmap
            EML-Template-main/release/latest.yml
